"""
Unified preprocessing module for AmbiDrop.

Converts raw ex_N/ folders (generated by datagenerator/*.py) to preprocessed
.pt files for model training and inference.

Data types
----------
Type A  generate_ambidrop_train_ds.py  — ideal SH only: anm.mat
Type B  generate_baseline_train_ds.py  — mic signals only: p.wav, pDirect.wav
Type C  generate_inference_ds.py       — full: p.wav, pDirect.wav, anm.mat (all three fields)

Usage
-----
from ambidrop.preprocess import (
    preprocess_mic, preprocess_sh_stft, preprocess_sh_time, preprocess_dataset
)

# Batch-preprocess a folder of ex_N/ subfolders:
preprocess_dataset(
    raw_root="datasets/inference_ds/my_array",
    out_root="datasets/inference_ds/my_array_mic",
    preprocess_fn=preprocess_mic,
    ref_id=0, array_name="my_array", train=False,
)
"""

import os
from pathlib import Path
from typing import Union

import numpy as np
import scipy.io
import soundfile as sf
import torch
from tqdm import tqdm

from ambidrop.constants import N_FFT, HOP_LENGTH, WIN_LENGTH
from ambidrop.signal_utils import complex_acn_to_real_acn

# Default signal lengths
_TRAIN_LEN = 96_000    # 6 s at 16 kHz
_TEST_LEN  = 120_000   # 7.5 s at 16 kHz


# ── Private helpers ───────────────────────────────────────────────────────────

def _load_raw(ex_dir: Union[str, Path]) -> dict:
    """Load all available signals from an ex_N/ folder as numpy arrays."""
    ex_dir = Path(ex_dir)
    result = {}

    p_path       = ex_dir / "p.wav"
    pdirect_path = ex_dir / "pDirect.wav"
    anm_path     = ex_dir / "anm.mat"

    if p_path.exists():
        data, _ = sf.read(str(p_path))
        result["p"] = data.T.astype(np.float32)          # (M, T)

    if pdirect_path.exists():
        data, _ = sf.read(str(pdirect_path))
        result["pDirect"] = data.T.astype(np.float32)    # (M, T)

    if anm_path.exists():
        mat = scipy.io.loadmat(str(anm_path))
        result["anmt"]        = mat["anmt"].T.astype(np.complex64)        # (9, T)
        result["anmtDirect"]  = mat["anmtDirect"].T.astype(np.complex64)  # (1, T)
        if "anmt_array" in mat:
            result["anmt_array"] = mat["anmt_array"].T.astype(np.complex64)  # (9, T)

    return result


def _find_onset(signal_ct: np.ndarray, threshold: float = 1e-3) -> int:
    """Return sample index of the first value in channel 0 that exceeds threshold."""
    nonzero = np.where(np.abs(signal_ct[0]) > threshold)[0]
    return int(nonzero[0]) if len(nonzero) > 0 else 0


def _slice(array_ct: np.ndarray, start: int, length: int) -> np.ndarray:
    """Slice (C, T) array from start, zero-padding if shorter than length."""
    sliced = array_ct[:, start:start + length]
    if sliced.shape[1] < length:
        sliced = np.pad(sliced, ((0, 0), (0, length - sliced.shape[1])))
    return sliced[:, :length]


def _window_pair(noisy_ct: np.ndarray, clean_ct: np.ndarray, train: bool,
                 onset: int = None) -> tuple:
    """
    Window a (noisy, clean) pair to the canonical length.
    train=True  — onset-based 6 s window (always starts from first speech frame).
    train=False — full signal returned as-is (no trimming, no onset detection).
    """
    if not train:
        return noisy_ct, clean_ct
    if onset is None:
        onset = _find_onset(clean_ct)
    return _slice(noisy_ct, onset, _TRAIN_LEN), _slice(clean_ct, onset, _TRAIN_LEN)


def _stft(signal_ct: np.ndarray) -> torch.Tensor:
    """
    Compute STFT of a multichannel signal (C, T), real or complex.
    For complex input, STFTs of real and imaginary parts are combined
    (matches the convention used in FT_JNF/train.py and utils/SH_data_process.py).
    Returns: (T_frames, F=257, C) complex torch tensor.
    """
    C = signal_ct.shape[0]
    window = torch.hamming_window(WIN_LENGTH)
    stft_kwargs = dict(
        n_fft=N_FFT, hop_length=HOP_LENGTH, win_length=WIN_LENGTH,
        window=window, center=True, normalized=False, onesided=True,
        return_complex=True,
    )
    is_complex = np.iscomplexobj(signal_ct)
    frames = []
    for c in range(C):
        ch = signal_ct[c]
        ch_r = torch.from_numpy(ch.real.astype(np.float32))
        if is_complex:
            ch_i = torch.from_numpy(ch.imag.astype(np.float32))
            stft_ch = torch.stft(ch_r, **stft_kwargs) + 1j * torch.stft(ch_i, **stft_kwargs)
        else:
            stft_ch = torch.stft(ch_r, **stft_kwargs)
        frames.append(stft_ch)          # (F, T_frames)
    return torch.stack(frames, dim=0).permute(2, 1, 0)  # (T_frames, F, C)


def _normalize_split(stft_complex: torch.Tensor, clean_ct: np.ndarray) -> tuple:
    """
    Normalize by STFT amplitude and split real/imag.

    Parameters
    ----------
    stft_complex : (T_frames, F, C) complex tensor — noisy STFT
    clean_ct     : (C', T) numpy array — clean time-domain signal

    Returns
    -------
    noisy_tf  : (T_frames, F, 2C) float tensor  (real cat imag)
    clean_t   : (C', T) float tensor
    max_val   : float
    """
    max_val = stft_complex.abs().max().item()
    if max_val == 0.0:
        max_val = 1.0
    stft_norm = stft_complex / max_val
    noisy_tf  = torch.cat([stft_norm.real, stft_norm.imag], dim=-1)   # (T, F, 2C)
    clean_t   = torch.from_numpy(clean_ct.real.astype(np.float32)) / max_val
    return noisy_tf, clean_t, max_val


# ── Public functions ──────────────────────────────────────────────────────────

def preprocess_mic(ex_dir, ref_id: int, array_name: str = "", ex_id: str = "",
                   train: bool = True) -> dict:
    """
    Preprocess microphone-domain data for FT-JNF Baseline and IC Conv-TasNet Baseline.

    Reads p.wav (noisy, sensor noise already present) and pDirect.wav (clean direct-path).
    Both files must exist in ex_dir (Type B or Type C folder).

    Parameters
    ----------
    ex_dir     : path to an ex_N/ folder
    ref_id     : reference microphone index (0-based); stored in dict for train.py
    array_name : stored in dict for logging
    train      : True → onset-based 6 s window; False → 7.5 s from start

    Returns
    -------
    dict with keys: noisy (T,F,2M), clean (M,T_s), ref_id, array_name, ex_id
    Compatible with FT_JNF.datasets.SimDS_preprocessed and ConvTasNet.datasets.SimDS_preprocessed.
    """
    raw = _load_raw(ex_dir)
    if "p" not in raw or "pDirect" not in raw:
        raise FileNotFoundError(f"p.wav or pDirect.wav missing in {ex_dir}")

    noisy_ct, clean_ct = _window_pair(raw["p"], raw["pDirect"], train)
    stft_noisy = _stft(noisy_ct)
    noisy_tf, clean_t, _ = _normalize_split(stft_noisy, clean_ct)

    return {
        "noisy":      noisy_tf,    # (T_frames, F, 2M)
        "clean":      clean_t,     # (M, T_samples)
        "ref_id":     ref_id,
        "array_name": array_name,
        "ex_id":      ex_id,
    }


def preprocess_sh_stft(ex_dir, anm_source: str = "ideal", ref_id: int = 0,
                       array_name: str = "", ex_id: str = "", train: bool = True) -> dict:
    """
    Preprocess Ambisonics data in STFT format for FT-JNF AmbiDrop.

    Parameters
    ----------
    ex_dir      : path to ex_N/ folder (Type A for anm_source="ideal", Type C for "asm")
    anm_source  : "ideal" → training on anmt; "asm" → inference on anmt_array
    train       : True → onset-based 6 s window; False → 7.5 s from start

    Returns (anm_source="ideal"):
        dict with keys: noisy (T,F,18), clean (T_s,), ref_id, array_name, ex_id

    Returns (anm_source="asm") — superset:
        same keys plus noisy_mic (T,F,14), clean_mic (M,T_s)
        FT_JNF/test_simulated.py branches on `'noisy_mic' in data` to compute
        noisy SI-SDR in the mic domain and enhanced SI-SDR in the SH domain.
    """
    raw = _load_raw(ex_dir)
    if "anmt" not in raw:
        raise FileNotFoundError(f"anm.mat missing in {ex_dir}")

    # Compute onset once from clean SH signal; reuse for all arrays
    onset = _find_onset(raw["anmtDirect"]) if train else None

    if anm_source == "ideal":
        noisy_ct, clean_ct = _window_pair(raw["anmt"], raw["anmtDirect"], train, onset)
    elif anm_source == "asm":
        if "anmt_array" not in raw:
            raise KeyError(f"anmt_array key missing in anm.mat in {ex_dir}")
        noisy_ct, clean_ct = _window_pair(raw["anmt_array"], raw["anmtDirect"], train, onset)
    else:
        raise ValueError(f"anm_source must be 'ideal' or 'asm', got {anm_source!r}")

    stft_noisy = _stft(noisy_ct)
    noisy_tf, clean_t, _ = _normalize_split(stft_noisy, clean_ct)
    clean_t = clean_t.squeeze(0)  # (1, T_s) → (T_s,)

    result = {
        "noisy":      noisy_tf,    # (T_frames, F, 18)
        "clean":      clean_t,     # (T_samples,) — a00 direct path
        "ref_id":     ref_id,
        "array_name": array_name,
        "ex_id":      ex_id,
    }

    if anm_source == "asm":
        if "p" not in raw or "pDirect" not in raw:
            raise FileNotFoundError(
                f"p.wav / pDirect.wav missing in {ex_dir} (required for anm_source='asm')"
            )
        mic_noisy_ct, mic_direct_ct = _window_pair(raw["p"], raw["pDirect"], train, onset)
        stft_mic = _stft(mic_noisy_ct)
        noisy_tf_mic, clean_t_mic, _ = _normalize_split(stft_mic, mic_direct_ct)
        result["noisy_mic"] = noisy_tf_mic   # (T_frames, F, 14) — mic STFT for noisy SI-SDR
        result["clean_mic"] = clean_t_mic    # (M, T_samples)   — mic clean for noisy SI-SDR

    return result


def preprocess_sh_time(ex_dir, ex_id: str = "", train: bool = True) -> tuple:
    """
    Preprocess ideal Ambisonics to real-valued ACN time-domain for IC Conv-TasNet AmbiDrop.
    Training only — for inference use MicToRealAmbisonicsDataset on raw p.wav.

    Parameters
    ----------
    ex_dir : path to ex_N/ folder (Type A — must contain anm.mat with anmt / anmtDirect)

    Returns
    -------
    (real_acn, clean_time)
      real_acn   : Tensor(9, T_samples) float32 — real-valued ACN Ambisonics
      clean_time : Tensor(T_samples,)   float32 — a00 direct path, same scale
    """
    raw = _load_raw(ex_dir)
    if "anmt" not in raw:
        raise FileNotFoundError(f"anm.mat missing in {ex_dir}")

    onset = _find_onset(raw["anmtDirect"]) if train else None
    noisy_ct, clean_ct = _window_pair(raw["anmt"], raw["anmtDirect"], train, onset)

    real_acn = complex_acn_to_real_acn(noisy_ct, max_order=2, sn3d=False)  # (9, T) real
    real_acn_t = torch.from_numpy(real_acn.astype(np.float32))
    clean_t    = torch.from_numpy(clean_ct[0].real.astype(np.float32))     # (T,)

    max_val = real_acn_t.abs().max().item()
    if max_val == 0.0:
        max_val = 1.0
    return real_acn_t / max_val, clean_t / max_val


def preprocess_dataset_multi(array_configs: list, out_root, preprocess_fn,
                             skip_existing: bool = True, **shared_kwargs) -> None:
    """
    Preprocess multiple array directories into a single merged output directory.

    Examples from all arrays are globally renumbered as ex_1.pt, ex_2.pt, … so they
    can be loaded by SimDS_preprocessed as a single flat dataset. Each .pt file stores
    the array_name and ref_id inside, so the training step picks the right reference mic.

    Parameters
    ----------
    array_configs : list of dicts, each with:
                      'raw_dir'    : path to folder containing ex_N/ subfolders (required)
                      'array_name' : label stored in each .pt (required for mic data)
                      'ref_id'     : mic reference index stored in each .pt (default 0)
                      any other key overrides the corresponding value in shared_kwargs
    out_root      : single output directory; examples written as ex_1.pt, ex_2.pt, …
    preprocess_fn : one of preprocess_mic / preprocess_sh_stft / preprocess_sh_time
    skip_existing : skip output files that already exist (safe for re-runs / appending)
    shared_kwargs : applied to all arrays; per-array dict values take priority
    """
    out_root = Path(out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    global_idx = 1
    for cfg in array_configs:
        raw_dir = Path(cfg["raw_dir"])
        per_array = {k: v for k, v in cfg.items() if k != "raw_dir"}
        kwargs = {**shared_kwargs, **per_array}

        ex_dirs = sorted(
            [d for d in raw_dir.iterdir() if d.is_dir() and d.name.startswith("ex_")],
            key=lambda d: int(d.name.split("_")[1]),
        )
        label = per_array.get("array_name", raw_dir.name)
        print(f"  {label}: {len(ex_dirs)} examples → ex_{global_idx} … ex_{global_idx + len(ex_dirs) - 1}")

        for ex_dir in tqdm(ex_dirs, desc=label):
            out_path = out_root / f"ex_{global_idx}.pt"
            if not (skip_existing and out_path.exists()):
                call_kwargs = dict(kwargs)
                call_kwargs.setdefault("ex_id", ex_dir.name)
                try:
                    result = preprocess_fn(ex_dir, **call_kwargs)
                    torch.save(result, str(out_path))
                except Exception as e:
                    print(f"  [Error] {ex_dir}: {e}")
            global_idx += 1


def preprocess_dataset(raw_root, out_root, preprocess_fn, skip_existing: bool = True,
                       **kwargs) -> None:
    """
    Batch-process every ex_N/ subfolder in raw_root and save results as .pt files.

    Parameters
    ----------
    raw_root       : directory containing ex_1/, ex_2/, … subfolders
    out_root       : directory where ex_1.pt, ex_2.pt, … will be written
    preprocess_fn  : one of preprocess_mic / preprocess_sh_stft / preprocess_sh_time
    skip_existing  : skip ex_N.pt files that already exist in out_root
    **kwargs       : forwarded to preprocess_fn (e.g. ref_id=0, anm_source="ideal", train=True)
    """
    raw_root = Path(raw_root)
    out_root = Path(out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    ex_dirs = sorted(
        [d for d in raw_root.iterdir() if d.is_dir() and d.name.startswith("ex_")],
        key=lambda d: int(d.name.split("_")[1]),
    )
    if not ex_dirs:
        raise ValueError(f"No ex_N/ subfolders found in {raw_root}")

    for ex_dir in tqdm(ex_dirs, desc=f"Preprocessing {raw_root.name}"):
        out_path = out_root / f"{ex_dir.name}.pt"
        if skip_existing and out_path.exists():
            continue
        call_kwargs = dict(kwargs)
        call_kwargs.setdefault("ex_id", ex_dir.name)
        result = preprocess_fn(ex_dir, **call_kwargs)
        torch.save(result, str(out_path))
